### ISSUE TITLE
mtDNA GATK filters

### ISSUE THREAD

**Issue by gemmabv** [rtonda/caseSummarizer#5]
Looks like filters are not correct. In case AS5845 case summarizer reports 0 variants as reported and I get 4.

/scratch/production/gbullich/NAGEN/casesummarizer/NAGENPEDIATRICS_90/NP245
![Screenshot 2022-11-21 at 14 52 07](https://user-images.githubusercontent.com/57441807/203072083-76245e1b-c005-4765-8b3c-6101a62fe499.png)

**Comment by lmatalonga** [comment]
Hi @gemmabv , 
Sorry this was an issue in the SOP -  AF mitomap < 0.5 (columna Z) and not 5.
Best, 
Leslie

**Comment by rtonda** [comment]
Hi,
I've checked in the code and the threshold used is <=0.5
